spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:correctionDB
    username: root
    password: pass
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
